Web/Chess.Web/Controllers/GameController.cs
namespace Chess.Web.Controllers
{
    using Chess.Services.Data.Services.Contracts;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class GameController : BaseController
    {
        private readonly IGameService gameService;

        public GameController(IGameService gameService)
        {
            this.gameService = gameService;
        }

        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/Chess.Web/Controllers/StatsController.cs
namespace Chess.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;

    using Chess.Data.Models;
    using Chess.Services.Data.Services.Contracts;
    using Chess.Web.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class StatsController : BaseController
    {
        private readonly IStatsService statsService;
        private readonly UserManager<UserEntity> userManager;

        public StatsController(IStatsService statsService, UserManager<UserEntity> userManager)
        {
            this.statsService = statsService;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var stats = this.statsService.GetUserStats<UserStatsViewModel>(userId);

            if (stats == null)
            {
                return this.RedirectToAction("Index", "Home");
            }

            var model = new StatsViewModel
            {
                UserName = this.User.Identity.Name,
                UserStats = stats,
                TotalUsers = this.userManager.Users.Count(),
                LastThirtyDaysRegisteredUsers = this.userManager.Users.Where(x => x.CreatedOn >= DateTime.Now.AddDays(-30)).Count(),
                TotalGames = this.statsService.GetTotalGames(),
                MostGamesUser = this.statsService.GetMostGamesUser(),
                MostWinsUser = this.statsService.GetMostWinsUser(),
            };

            return this.View(model);
        }
    }
}

Web/Chess.Web/Views/Shared/_Layout.cshtml
@using Chess.Common.Constants

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @CommonConstants.SystemName</title>
    <link rel="apple-touch-icon" href="~/apple-touch-icon.png"/>

    <environment names="Development">
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/style.min.css" asp-append-version="true" />
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-chess-knight" style="font-size: 25px; color: #454a52;"></i>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Стартовая страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Game" asp-action="Index">Играть</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Stats" asp-action="Index">Статистика</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="body-renderer container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>

    <environment names="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="https://kit.fontawesome.com/67c59dfcad.js" asp-append-version="true" crossorigin="anonymous"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
        <script src="https://kit.fontawesome.com/67c59dfcad.js" asp-append-version="true" crossorigin="anonymous"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>